import axios from "axios";
import { GREENBOOK_BASE_URL } from "@/lib/constants";
import { normalizeNafdacNumber } from "@/lib/normalize-nafdac-number";
import { GreenbookResponseSchema } from "@/schemas/nafdac.schema";

function buildGreenbookParams(nafdacNumber: string) {
  return {
    draw: 1,
    "columns[0][data]": "product_name",
    "columns[0][name]": "product_name",
    "columns[0][searchable]": "true",
    "columns[0][orderable]": "true",
    "columns[0][search][value]": "",
    "columns[0][search][regex]": "false",
    "columns[1][data]": "ingredient.ingredient_name",
    "columns[1][name]": "ingredient.ingredient_name",
    "columns[1][searchable]": "true",
    "columns[1][orderable]": "true",
    "columns[1][search][value]": "",
    "columns[1][search][regex]": "false",
    "columns[2][data]": "product_category.name",
    "columns[2][name]": "product_category.name",
    "columns[2][searchable]": "true",
    "columns[2][orderable]": "false",
    "columns[2][search][value]": "",
    "columns[2][search][regex]": "false",
    "columns[3][data]": "product_category_id",
    "columns[3][name]": "product_category_id",
    "columns[3][searchable]": "true",
    "columns[3][orderable]": "true",
    "columns[3][search][value]": "",
    "columns[3][search][regex]": "false",
    "columns[4][data]": "ingredient.synonym",
    "columns[4][name]": "ingredient.synonym",
    "columns[4][searchable]": "true",
    "columns[4][orderable]": "true",
    "columns[4][search][value]": "",
    "columns[4][search][regex]": "false",
    "columns[5][data]": "NAFDAC",
    "columns[5][name]": "NAFDAC",
    "columns[5][searchable]": "true",
    "columns[5][orderable]": "true",
    "columns[5][search][value]": normalizeNafdacNumber(nafdacNumber),
    "columns[5][search][regex]": "false",
    "columns[6][data]": "form.name",
    "columns[6][name]": "form.name",
    "columns[6][searchable]": "true",
    "columns[6][orderable]": "true",
    "columns[6][search][value]": "",
    "columns[6][search][regex]": "false",
    "columns[7][data]": "route.name",
    "columns[7][name]": "route.name",
    "columns[7][searchable]": "true",
    "columns[7][orderable]": "true",
    "columns[7][search][value]": "",
    "columns[7][search][regex]": "false",
    "columns[8][data]": "strength",
    "columns[8][name]": "strength",
    "columns[8][searchable]": "true",
    "columns[8][orderable]": "true",
    "columns[8][search][value]": "",
    "columns[8][search][regex]": "false",
    "columns[9][data]": "applicant.name",
    "columns[9][name]": "applicant.name",
    "columns[9][searchable]": "true",
    "columns[9][orderable]": "true",
    "columns[9][search][value]": "",
    "columns[9][search][regex]": "false",
    "columns[10][data]": "approval_date",
    "columns[10][name]": "approval_date",
    "columns[10][searchable]": "true",
    "columns[10][orderable]": "true",
    "columns[10][search][value]": "",
    "columns[10][search][regex]": "false",
    "columns[11][data]": "status",
    "columns[11][name]": "status",
    "columns[11][searchable]": "true",
    "columns[11][orderable]": "true",
    "columns[11][search][value]": "",
    "columns[11][search][regex]": "false",
    "order[0][column]": 5,
    "order[0][dir]": "asc",
    start: 0,
    length: 10,
    "search[value]": "",
    "search[regex]": "false",
    search_ingredient: "",
    _: Date.now(),
  };
}

export async function searchGreenbookByNafdacNumber(nafdacNumber: string) {
  const response = await axios.get(GREENBOOK_BASE_URL, {
    params: buildGreenbookParams(nafdacNumber),
    headers: {
      Accept: "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
    },
    timeout: 12_000,
  });

  return GreenbookResponseSchema.parse(response.data);
}
